models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $reCaptcha;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['reCaptcha'], 'required'],
            // email has to be a valid email address
            [['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator2::className(),
                'uncheckedMessage' => 'Please confirm that you are not a bot.'
                ],

        ];
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\ContactForm;
use app\components\TreeHandler;
use app\components\GiphyClient;
use yii\helpers\Url;


class SiteController extends Controller
{

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        $model = new ContactForm();
        $treeHandler = new TreeHandler();
        $nodesCount = rand(100, 1000);
        $this->getView()->registerJsFile('js/jquery.js');
        $this->getView()->registerJsVar('ajaxFormUrl', Url::toRoute(['ajaxform']));
        $this->getView()->registerJsFile('js/popup.js');

        return $this->render('index', [
            'tree' => $treeHandler->getRandomTree($nodesCount),
            'model' => $model,
        ]);
    }

    public function actionAjaxform(){
        $model = new ContactForm();
        return $this->render('ajax', [
            'model' => $model,
        ]);
    }

    public function actionImage(){

        if(Yii::$app->request->isPost)
        {
            $giphyClient = new GiphyClient();
            $this->layout = false;
            return $this->render('image', [
                'url' => $giphyClient->getRandomImageUrl()
            ]);
        }

    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <div class="container">

        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/ajax.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

?>

<?php
$this->registerJs(
    '$("document").ready(function(){
            $("#new_note").on("pjax:end", function() {
            $.pjax.reload({container:"#notes"});  //Reload GridView
        });
    });'
);
?>


</div>
<?php yii\widgets\Pjax::begin(['id' => 'new_note']) ?>

<?php $form = ActiveForm::begin(['action' => Url::toRoute(['site/image']), 'id' => 'contact-form', 'options' => ['data-pjax' => true]]);

?>

<input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>"/>

<div id="notes">
    <?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha2::className(), [
        'name' => 'reCaptcha',
    ]) ?>


    <div class="form-group">
        <?= Html::submitButton('Continue', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
    </div>
</div>


<?php ActiveForm::end(); ?>
<?php Pjax::end(); ?>

views/site/image.php
<image src="<?php echo $url;?>"></image>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
$this->title = 'My Yii Application';
?>
<div class="site-index">

        <div class="popup">
            <a class="close" href="#">&times;</a>
            <div class="content">

            </div>
        </div>

    <div class="body-content">
        <?php
        $func = function($tree) use (&$func){
            echo "<ul>";
            foreach ($tree as $key => $value) {
                echo "<li>";
                echo "<a href='#' id='' class='node'>$key</a>";
                if(is_array($value)){
                    $func($value);
                }
                echo "</li>";
            }
            echo "</ul>";
        };
        $func($tree);
        ?>
    </div>


</div>